### ISSUE TITLE
Update documentation to showcase class syntax.

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-decorators#120]
Need to update the following files to showcase native ES `class` syntax primarily with a secondary example showing the existing `.extend()` syntax (and including the `@decorator foo: null` work around as required).

- [ ] `ember-decorators/controller`
- [ ] `ember-decorators/data`
- [ ] `ember-decorators/object`
- [ ] `ember-decorators/object/computed`
- [ ] `ember-decorators/object/evented`
- [ ] `ember-decorators/service`

**Comment by pzuraq** [comment]
Think we should remove the Before/After examples as well, and have an overarching Before/After in the main Readme? The API docs are getting fairly verbose as is.

**Comment by rwjblue** [comment]
> Think we should remove the Before/After examples as well

Ya, this makes sense to me.  IMO, the "examples" per item should basically be showing how to use the decorators (it isn't our job to teach folks the underlying Ember concepts here).

**Comment by buschtoens** [comment]
And what about calling super methods?

```js
didReceiveAttrs() {
  this._super(...arguments);
  // ...
}
```

vs

```js
didReceiveAttrs() {
  super.didReceiveAttrs(...arguments);
  // ..
}
```

Does the latter even work?

**Comment by buschtoens** [comment]
As it turns out, the latter form (`super.didReceiveAttrs`) is apparently *required*.

**Comment by pzuraq** [comment]
We should make aure that standard class super style works for every method, it should be required. That's really weird, will look into it.

**Comment by rwjblue** [comment]
Standard super is the way to go. this means `super(...)` for `constructor` and `super.whateverMehtod()` everywhere else.
