### ISSUE TITLE
Request: deprecatingAlias

### ISSUE THREAD

**Issue by buschtoens** [rwjblue/ember-decorators#127]
[API docs for `Ember.computed.deprecatingAlias`](https://www.emberjs.com/api/ember/2.14/namespaces/Ember.computed/methods/deprecatingAlias?anchor=deprecatingAlias)

Usage:

```diff
import Component from '@ember/component';
-import { deprecatingAlias } from '@ember/object/computed';
+import { deprecatingAlias } from 'ember-decorators/object/computed';

export default class extends Component {
  newProperty;

-  deprecatedProperty = deprecatingAlias('newProperty', {
-    id: 'foo-deprecation',
-    until: '1.0.0',
-    link: 'https://example.com/deprecations/foo-deprecation
-  });
+  @deprecatingAlias('newProperty', {
+    id: 'foo-deprecation',
+    until: '1.0.0',
+    link: 'https://example.com/deprecations/foo-deprecation
+  })
+  deprecatedProperty;
}
```

I'd submit a PR, if this is a welcome addition. :slightly_smiling_face:

**Comment by pzuraq** [comment]
I think this would be a good addition. I would like to strip it from production builds with a babel transform and replace it with a normal `@alias` decorator so we avoid creating the options object and the extra overhead, but given the purpose of the decorator I think we can go with the simple implementation for now and add the transform to remove it later on.

**Comment by Cryrivers** [comment]
@pzuraq i can help it (decorator + babel transformer)

**Comment by rwjblue** [comment]
We can use ember-cli-babel's built in `import { DEBUG } from '@glimmer/env'` to detect if we are in a debug build, and change which underlying implementation to use. 

:+1: on this
