### ISSUE TITLE
Actions inherited from non es6 class get overwritten

### ISSUE THREAD

**Issue by blmundie** [rwjblue/ember-decorators#128]
If you have actions in a parent class that isn't an es6 class declaration and you use the @action decorator it overwrites all of the parent class actions.

**Comment by pzuraq** [comment]
ah, actions are a `merged` property aren't they? We'll need to account for that, I think we can update the decorator to do it for us for now.

**Comment by rwjblue** [comment]
Yes, confirm it is a merged property. We can either just call `.proto()` or try to emulate the mixin system. Generally though I'd prefer to avoid adding more bonkersness from the Ember object model.
