### ISSUE TITLE
Documentation - import reference incorrect

### ISSUE THREAD

**Issue by linearza** [rwjblue/ember-decorators#129]
The documentation for individual computed decorators use the wrong import in the example snippets: ```import { alias } from 'ember-decorators/computed';```

Whereas it only seems to work with the syntax used in the other examples:
```import { alias } from 'ember-decorators/object/computed';```

**Comment by rwjblue** [comment]
Good catch! Would you mind submitting a PR to fix?

**Comment by linearza** [comment]
PR created. Thanks for a great plugin!
