### ISSUE TITLE
filter, map, sort: use descriptor value as callback

### ISSUE THREAD

**Issue by buschtoens** [rwjblue/ember-decorators#138]
Currently [`filter(dependentKey, callback)`](https://rwjblue.github.io/ember-decorators/docs/function/addon/object/computed.js.html#static-function-filter), [`map(dependentKey, callback)`](https://rwjblue.github.io/ember-decorators/docs/function/addon/object/computed.js.html#static-function-map) and [`sort(dependentKey, sortDefinition)`](https://rwjblue.github.io/ember-decorators/docs/function/addon/object/computed.js.html#static-function-sort) all expect the callback function to be passed as the last argument, just like their `Ember.computed` counterparts. This makes for (subjectively) ugly syntax and nagged me since day one.

I propose that we make the callback argument optional (for these three decorators only) and fallback to the descriptor value. Just like we normally do for `@computed`.

This would allow this syntax:

```js
import EmberObject from '@ember/object';
import { A } from '@ember/array';
import {filter, sort} from 'ember-decorators/object/computed'

export default class extends EmberObject {
  chores = A([
    { name: 'cook', done: true },
    { name: 'clean', done: true },
    { name: 'write more unit tests', done: false }
  ]);

  @filter('chores')
  remainingChores(chore, index, array) {
    return !chore.done;
  }

  @map('chores')
  loudChores(chore, index) {
    return chore.name.toUpperCase() + '!';
  }

  @sort('names')
  sortedNames(a, b) {
    if (a.name > b.name) {
      return 1;
    } else if (a.name < b.name) {
      return -1;
    }

    return 0;
  }
}
```

Only falling back to the descriptor value when the callback argument is empty has two advantages:

- full backwards compatibility
- hypothetical composability still possible (#99)

Yay or nay? I can try to submit a PR. :slightly_smiling_face:

**Comment by rwjblue** [comment]
Definitely 👍 from me.  

@pzuraq - Thoughts?

**Comment by pzuraq** [comment]
I'm on board, would be much cleaner than it is now
