### ISSUE TITLE
Re-export `raw` from ember-macro-helpers

### ISSUE THREAD

**Issue by buschtoens** [rwjblue/ember-decorators#144]
https://github.com/rwjblue/ember-decorators/issues/58#issuecomment-317849968

What would the appropriate module name be?

**Comment by pzuraq** [comment]
Not sure we want to tie ourselves more to ember-macro-helpers if class getters/setters are the future

**Comment by pzuraq** [comment]
Based on #146 it looks like we'll be pulling `ember-macro-helpers` based decorators out into a separate addon, so closing this for now. We can reopen once that addon is up
