### ISSUE TITLE
Doesn't work with babel-core 5.5.0+ (latest: 5.5.6)

### ISSUE THREAD

**Issue by devinus** [rwjblue/ember-decorators#24]
This commit changed the interface: https://github.com/babel/babel/commit/1934c16f0f477ff5a5f75688e49477fe6c983690

**Comment by stefanpenner** [comment]
That doesn't seem correct. Hmm

**Comment by rwjblue** [comment]
We are using initializer in a number of places, seems like that would be an issue with the commit linked above. 

@stefanpenner - Are you saying it doesn't seem correct in Babel, or something else?

**Comment by devinus** [comment]
Would it be acceptable to lock in the version of `babel-core` to `5.4.7` for now?

**Comment by stefanpenner** [comment]
Yup. You should be able to do this from userland

**Comment by stefanpenner** [comment]
I can likely address this by tomorkw

**Comment by devinus** [comment]
@stefanpenner This is possible without locking in upstream?

**Comment by stefanpenner** [comment]
> @stefanpenner This is possible without locking in upstream?

pining it in you apps package.json should do the trick, just nom and be on a recent NPM version

**Comment by devinus** [comment]
@stefanpenner I'm not sure you can pin a dependencies' depdencies' dependency in your package.json, can you?

**Comment by stefanpenner** [comment]
Yes. This is how the dedupe and resolution strategy work

**Comment by knownasilya** [comment]
Has this been fixed?

**Comment by stefanpenner** [comment]
> Has this been fixed?

nope

**Comment by rwjblue** [comment]
Seems resolved now.
