### ISSUE TITLE
Use machty's jshint guard hax

### ISSUE THREAD

**Issue by machty** [rwjblue/ember-decorators#25]
There might be some not-yet-handled edge cases but I think this should do the trick:

https://github.com/machty/broccoli-es7-decorator-jshint-guards

@rwjblue and I talked about this and he suggested using and re-exporting the above in ember-computed-decorators. I was gonna do this and then got busy (and I don't totally grok the test failures due to the recent Babel change).

**Comment by stefanpenner** [comment]
https://github.com/machty/broccoli-es7-decorator-jshint-guards/blob/master/index.js#L11 doesn't look sourceMap aware.

**Comment by rwjblue** [comment]
This transformation is done before any transpiration, which means that those lines will just be shown in the sourcemap output.

**Comment by stefanpenner** [comment]
ah yes, but they will be different from the input. It would be better if they where done as a babel plugin, that way it would be totally transparent.

**Comment by martndemus** [comment]
@stefanpenner Are there any babel plugins that do similar things? I don't think I can build something like this from scratch, but if there is something I can 'copy' from, then I might manage to do this.

**Comment by devinus** [comment]
I feel like instead ember-cli should switch to ESLint and use a ESLint plugin to understand decorators.

**Comment by stefanpenner** [comment]
> I feel like instead ember-cli should switch to babel-eslint to understand decorators.

this is likely the best solution for right now.

**Comment by SirZach** [comment]
any chance on using @machty code as a temporary means? not sure how far away #49 is to being completed and i would love to rip out all the hax. thanks!

**Comment by rwjblue** [comment]
#49 is only for updating this Addons linter to ESLint, and doesn't fix the problem for applications.

**Comment by rwjblue** [comment]
Also, in general I'm not opposed, but we need to figure out how to address the sourcemap concerns that @stefanpenner mentioned first.

**Comment by devinus** [comment]
I've updated my apps to use ESLint. It's glorious.

**Comment by SirZach** [comment]
@devinus could you go into more detail? do you not have jshint anymore and instead have eslint?
@rwjblue sometimes you gotta do something bad and ask for forgiveness later :)

**Comment by pzuraq** [comment]
Think this might be superceded by #106, which upgrades to ESLint
