### ISSUE TITLE
Unknown transformer es7.decorators specified in optional

### ISSUE THREAD

**Issue by denzo** [rwjblue/ember-decorators#35]
After I modify my Brocfile.js with the below I get a compile time error in Ember-CLI (v1.13.1)

```
var app = new EmberApp({
  babel: {
      optional: ['es7.decorators']
  }
});
```

**Comment by NullVoxPopuli** [comment]
I just got this too with Ember 2.11.1

**Comment by rwjblue** [comment]
Seems resolved.  Happy to reopen with a repro...
