### ISSUE TITLE
'computed' export shouldn't be default.

### ISSUE THREAD

**Issue by optikalefx** [rwjblue/ember-decorators#63]
This is more of an es6 qualm, but I think it was be simpler to use if there was no default exported.

So this syntax

`import computed, { readOnly } from 'ember-computed-decorators';` Which is odd to write, would become

`import { computed, readOnly } from 'ember-computed-decorators';`

and 

`import { computed } from 'ember-computed-decorators';`

**Comment by pzuraq** [comment]
We've updated the exports to match the upcoming [Ember module api](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md). It's now:

```
import { computed } from 'ember-decorators/object';
import { readOnly } from 'ember-decorators/object/computed';
```

Checkout [the docs](https://rwjblue.github.io/ember-decorators/docs/index.html) for the current imports!
