### ISSUE TITLE
allow for dependencies on attrs but receive the object as the argument

### ISSUE THREAD

**Issue by SirZach** [rwjblue/ember-decorators#66]
I have the following setup:

```
@computed('somePromise.isFulfilled')
cpBasedOnPromise(promise) {
  //promise here is just the value true or false, not the promise itself
}
```

In this instance I don't want the value of `isFulfilled`, I want the value of the promise but I want the computed property dependent on if the promise is fulfilled or not.

**Comment by pzuraq** [comment]
This is more of an issue with kellyselden/ember-macro-helpers, this library just wraps its `computed` macro.

**Comment by pzuraq** [comment]
Closing this as we will be deprecating the ember-macro-helpers behavior in favor of ES class getters/setters (see #146). I recommend reopening upstream if you still think it's an issue.

**Comment by kellyselden** [comment]
@pzuraq After ember-macro-helpers is removed, users are responsible for doing all `this.get` stuff themselves?

**Comment by pzuraq** [comment]
Unfortunately yes, it's not going to be an option if we use native getters and setters, the arity is restricted and adding any parameters to a getter is a syntax error.

That said, I think we definitely should pull the existing decorators and their behavior out into an addon specifically to wrap `ember-macro-helpers`. If users like the macro-helpers style, they should be able to use them, and then we can focus on the issues with those such as compose-ability.

@rwjblue and I are planning on pulling out some shared decorator helpers (the macro functions) as well, and creating a generic decorator addon (like `core-decorators`, not really ember-related decorators). We want to do this on a GitHub org though, and we're still bikeshedding on the name for the org 😛 if you'd like to have the `ember-macro-helpers` live on that org we can do it there, but also down to help out if you wanna make them now and skip the 🚲 🏠
