### ISSUE TITLE
ESLint undefined errors

### ISSUE THREAD

**Issue by rwwagner90** [rwjblue/ember-decorators#70]
How can I get ESLint to not flag things like this as undefined?

`@alias('user.address.validations.attrs.state.messages') stateErrorMessages,`

`error  'stateErrorMessages' is not defined  no-undef`

**Comment by brandonjmckay** [comment]
Could probably put `/*global stateErrorMessages*/` at the top of that file.
Not sure if that's the best way, but I think that would work.

**Comment by rwwagner90** [comment]
@brandonjmckay no, that won't work. I'd have to do that for every single variable, and would be incredibly tedious. The correct solution is to figure out how to fix ESLint to allow it.

**Comment by dbashford** [comment]
FYI https://github.com/rwjblue/ember-computed-decorators/issues/59#issuecomment-174417204

This isn't an issue for this library, and it doesn't look like its fixable in babel.

So you are left doing this:

`@alias('some.thing.long') propName: null`

**Comment by rwwagner90** [comment]
@dbashford yeah, I opened an issue on ESLint, since we'll probably need to tweak ESLint itself to make this work. Issue is here: https://github.com/eslint/eslint/issues/6775

**Comment by bartocc** [comment]
don't you think the readme should indicate that this syntax will cause this eslint error ?

**Comment by rwwagner90** [comment]
@rwjblue @bartocc should we update the README examples to just do like this?
```js
@empty('items') isEmpty: null
```

It would fix the issues with ESLint.
