### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by blmundie** [rwjblue/ember-decorators#91]
Is there a way to use this addon in visual studio code without js errors.  I enabled decorators, but it errors that the decorators aren't before a declaration.

~~~~
//no visual studio error
@computed("attr")
function testProp(attr) {
  return attr;
}
//error in visual studio code
Ember.Component.extend({
  @computed("attr")
  testProp(attr) {
    return attr;
  }
})
~~~~

**Comment by rwjblue** [comment]
I believe that the current version the decorator spec only allows them in classes. I'd have to confirm with @wycats though.
