### ISSUE TITLE
Add helper for addons to bootstrap parent app

### ISSUE THREAD

**Issue by thec0keman** [rwjblue/ember-decorators#92]
It would be nice if a helper was included with this addon for addons to bootstrap their parent app (described [here](https://github.com/rwjblue/ember-computed-decorators#setup-with-addon)).

This would especially be helpful for some of the API changes with Babel in Ember CLI (e.g. [here](https://github.com/rwjblue/ember-computed-decorators/issues/90)).

Would there be interest in accepting a PR for this?

**Comment by buschtoens** [comment]
Was closed by #121. Addons now handle transpilation themselves independent of the host app.

**Comment by rwjblue** [comment]
Awesome, thanks for spotting that @buschtoens!
