### ISSUE TITLE
Runtime error with @alias in service

### ISSUE THREAD

**Issue by NullVoxPopuli** [rwjblue/ember-decorators#93]
I'm in the process of upgrading to Ember 2.13.1, and I have this service:

```js
import Ember from 'ember';
import computed, { alias } from 'ember-computed-decorators';

export default Ember.Service.extend({
  // ...
  @alias('session.data.authenticated.id') id,
  @alias('user.name') name,
  // ...
```

which works fine on ember 2.9.x, but
on 2.13.1, when I load the app in the browser, I see this in console:

```
ember.debug.js:19829 ReferenceError: id is not defined
    at Module.callback (current-user.js:83)
    at Module.exports (loader.js:114)
    at requireModule (loader.js:29)
    at Class._extractDefaultExport (index.js:392)
    at Class.resolveOther (index.js:108)
    at Class.superWrapper [as resolveOther] (ember.debug.js:42849)
    at Class.resolve (ember.debug.js:7201)
    at resolve (ember.debug.js:4590)
    at Registry.resolve (ember.debug.js:4051)
    at Registry.resolve (ember.debug.js:4055)
```

which is weird, so I click the top of the trace, and see this:

```

  exports.default = _ember.default.Service.extend((_dec = (0, _emberComputedDecorators.alias)('session.data.authenticated.id'), _dec2 = (0, _emberComputedDecorators.alias)('user.name'), _dec3 = (0, _emberComputedDecorators.default)('user'), _dec4 = (0, _emberComputedDecorators.default)('user'), _dec5 = (0, _emberComputedDecorators.default)('session.data.authenticated.{token}'), (_obj = {
    session: service('session'),
    store: service(),

    id: id, // <- error points here
    name: name,
```

what's going on?

**Comment by NullVoxPopuli** [comment]
Here is my babel config in ember-cli-build:
```
    babel: {
      // ember < 2.13 / babel < 6
      // optional: ['es7.decorators'],
      // ember >= 2.13 / babel >= 6
      plugins: [
        'transform-decorators-legacy',
        'transform-decorators',
        'transform-object-rest-spread'
      ]
    },
```

**Comment by buschtoens** [comment]
Apparently `transform-decorators-legacy` works a bit differently and does not replace the original property, but instead calls `defineProperty` *on top*. At least that's what I reckon at a quick glance.

The obvious quick fix is jumping through the codebase and replacing all offending code:

```js
  @alias('session.data.authenticated.id') id,
  @alias('user.name') name

  // becomes

  @alias('session.data.authenticated.id') id: null,
  @alias('user.name') name: null
```

**Comment by rwjblue** [comment]
@buschtoens - Thank you chiming in here!   That definitely seems like a reasonable solution for folks blocked by this.  I'll need to read through the spec a bit more to see if the behavior babel@6 + transform-decorators-legacy is exhibiting is correct or a bug...

**Comment by NullVoxPopuli** [comment]
oh man. that would be a hefty change for me. I use the decorators everywhere. 
Thankfully, I'm not blocked, as this 2.13.1 upgrade is branched.

I know I can regex-replace all of them -- but lemme know if the non-object notation is gonna be the final one (the current notation ( `@alias('property') aliasedProperty` ) )

**Comment by rwjblue** [comment]
@NullVoxPopuli - Ya, I reached out to @wycats to double check the spec with me also.  Hopefully will have a more definite confirmation in a couple days...

**Comment by rwjblue** [comment]
I am going to close this for now.  The version of decorators that we are currently using (with babel-plugin-transform-decorators-legacy) is from the original proposal. The babel crew are actively working on updating for the current spec and hopefully we can migrate to that soon enough.  When we do, we will re-evaluate these sorts of issues...
